config/routes.rb
Rails.application.routes.draw do

  resources :users
  get '/signup' => 'users#new'

  resources :sessions

  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'

  resources :posts

 root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :user_name, presence: true
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def is_logged_in? 
  		if session[:user_id]
  		return true
  		else
  		return false
  		end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  attr_accessor :user_id
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    if is_logged_in?
    @post = Post.new
    else
      redirect_to '/signin/'
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
   # @post.attributes[:user_id] = session[:user_id]
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :slug, :title, :image_url, :content, :is_published)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	  user = User.find_by(email: params[:session][:email].downcase)
  if user && authenticate(user, params[:session][:password_digest])
    # Sign the user in and redirect to the user's show page.
    #flash[:error] = 'correct'
    #sign_in user
    session[:user_id] = user.id
    redirect_to user
  else
    # Create an error message and re-render the signin form.
    flash[:error] = 'Invalid email/password combination'
    render 'new'
  end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end

	private 
	def authenticate(user, password)
		if user.password_digest == password
			return true
		else
			return false	
			end	
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

  def show
  	
  	if(params[:id])
  		@user = User.find(params[:id])
  	else
  		@user = User.find(session[:user_id])
  	end
  end

  def new
  	@user = User.new
  end

   # GET /users/1/edit
  def edit
  end

  def create 
  	@user = User.new(user_params)    # Not the final implementation!
    if @user.save
      # Handle a successful save.
      user = User.find_by_email(@user.email)
      session[:user_id] = user.id
    else
      render 'new'
    end
  end

private
 	def user_params
    params.require(:user).permit(:user_name, :email, :password_digest, :image_url)
 	 end

 	 public
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def is_logged_in? 
  		if session[:user_id]
  		return true
  		else
  		return false
  		end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoRMedium</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<%= render 'posts/header' %>

<div class="container">
<%= yield %>
</div>


<%# <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div class="field">
<%#    <%= f.label :user_id %>
<%#    <%= f.number_field :user_id %>
  </div> -->
  <%= f.hidden_field :user_id, :value => session[:user_id]%>
  
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :is_published %><br>
    <%= f.check_box :is_published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("logo.png"), '/' %>
    </div>
	<ul class="nav navbar-nav navbar-right">
	<% if(!is_logged_in?) %>
		<li><%= link_to 'sign up', '/signup' %></li>
		<li><%= link_to 'sign in', '/signin' %></li>
		<% else %>
		<%# logged in as <%= session[:user_id] %>
		<% path = '/users/' + session[:user_id].to_s %>
		<li><%= link_to 'home', '/' %></li>
		<li><%= link_to 'my profile', path %> </li>
		<li><%= link_to 'authors', '/users/' %></li>
		<li><%= link_to 'Log out', '/signout', :method => :delete, data: { confirm: 'Are you sure?' } %></li>
		<% end %>
	</ul>
  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>
<% if is_logged_in? %>
<%= link_to 'New Post', new_post_path %>
<% end %>
<% @posts.each do |entry| %>
<% if entry.is_published %>
  <div class="row post_entry">
    <div class="post_image col-md-10 col-md-offset-1">
      <img src="images/<%= entry.image_url %>" alt="">
    </div>
    <div class="col-md-10 col-md-offset-1">
      <h3 class="post_title"><%= entry.title %> 
      <% if entry.user %>
      <span class="author_ref"><i>by</i> '<%= entry.user.user_name %>'</span>
      <% end %>
      </h3>
    </div>
    <div class="col-md-10 col-md-offset-1">
      <p class="post_content">
        <%= entry.content %>
      </p>
      <p><%= link_to 'Show', entry %> 
      <% if is_logged_in? && entry.user_id == session[:user_id] %>
       | <%= link_to 'Edit', edit_post_path(entry) %> 
       | <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
     
      </p>
    </div>
 
  </div>
  <% else %>

  <% end %>

<% end %>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @post.image_url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Is published:</strong>
  <%= @post.is_published %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/create.html.erb
<h3>Welcome</h3>
<img src="../images/<%= @user.image_url %>" alt="">
<p>Username: <%= @user.user_name %></p> 
<p>Email address: <%= @user.email %></p>	

 <p></p>

app/views/users/edit.html.erb
<%= form_for @user do |f|  %>



<% end %>

app/views/users/index.html.erb
<% @users.each do |entry|  %>
	<div class="row user_entry">
		<div class="col-md-3">
		<% if entry.image_url %>
			<img src="../images/<%= entry.image_url %>" alt="avatar">
		<% else %>
			<img src="../images/dummy_avatar.png" alt="">
		<% end %>
		</div>

		<div class="col-md-5">
			<ul class="user_entry_description">
				<li>Username: <%= entry.user_name %></li>
				<li>Email: <%= entry.email %></li>
				<li><%= link_to "details", "/users/#{entry.id}" %></li>
			</ul>
		</div>
	</div>
<% end %>

app/views/users/new.html.erb
<h1>Signup: </h1>
<div class="container">
	<div class="col-md-12">
		<%= form_for(@user) do |f| %>
		<p>
		<%= f.label :user_name %> <br>
		<%= f.text_field :user_name %>
		</p>

		<p>
			<%= f.label :email %> <br>
			<%= f.text_field :email %>
		</p>

		<p>
			<%= f.label :password_digest, "password"  %> <br>
			<%= f.password_field :password_digest %>
		</p>

		<p>
			<%= f.label :image_url  %> <br>
			<%= f.text_field :image_url  %>
		</p>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<img src="../images/<%= @user.image_url %>" alt="">
<p>Username: <%= @user.user_name %></p> 
<p>Email address: <%= @user.email %></p>	
<%= link_to '<< back', '/users/' %>
<% if session[:user_id] == @user.id %>
 | <%= link_to 'New Post', new_post_path %>
 | <%= link_to 'Edit profile', edit_user_path %>
<% end %>
<br>